apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: output
  params:
    - name: repo-url
      type: string
      default: "https://github.com/Aureo01/vselh-ci-cd-final-project-template"
    - name: app-name
      type: string
      default: "vselh-app"
    - name: build-image
      type: string
      default: "image-registry.openshift-image-registry.svc:5000/aureo01-dev/vselh-app"
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output
    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      runAfter: [cleanup]
      workspaces:
        - name: output
          workspace: output
      params:
        - name: url
          value: $(params.repo-url)
    - name: flake8
      taskRef:
        name: flake8
      runAfter: [git-clone]
      workspaces:
        - name: source
          workspace: output
    - name: nose
      taskRef:
        name: nose
      runAfter: [flake8]
      workspaces:
        - name: source
          workspace: output
    - name: buildah
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter: [nose]
      workspaces:
        - name: source
          workspace: output
      params:
        - name: IMAGE
          value: $(params.build-image)
    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter: [buildah]
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
